theme = "meliora"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
line-number = "relative"
shell = ["zsh", "-c"]

[editor.file-picker]
hidden = false
follow-symlinks = false

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.normal]
esc = ["collapse_selection", "normal_mode"]
"*" = ["move_prev_word_start", "move_next_word_end", "search_selection"]
G = "goto_file_end"
C-k = "signature_help"
K = "hover"

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.normal.space]
space = "file_picker"
