theme = "flatwhite"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
line-number = "relative"
shell = ["zsh", "-c"]

[editor.file-picker]
hidden = false
follow-symlinks = false

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.normal]
"*" = ["move_prev_word_start", "move_next_word_end", "search_selection"]

[keys.normal.space]
space = "file_picker"
